# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonmeister/1_SemesterIV/Operating_systems/Exam1/Exam1_OS_Scheduling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonmeister/1_SemesterIV/Operating_systems/Exam1/Exam1_OS_Scheduling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonmeister/1_SemesterIV/Operating_systems/Exam1/Exam1_OS_Scheduling/CMakeFiles /home/jonmeister/1_SemesterIV/Operating_systems/Exam1/Exam1_OS_Scheduling//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonmeister/1_SemesterIV/Operating_systems/Exam1/Exam1_OS_Scheduling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Exam1

# Build rule for target.
Exam1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Exam1
.PHONY : Exam1

# fast build rule for target.
Exam1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/build
.PHONY : Exam1/fast

Implementations/Algorithm.o: Implementations/Algorithm.cpp.o
.PHONY : Implementations/Algorithm.o

# target to build an object file
Implementations/Algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Algorithm.cpp.o
.PHONY : Implementations/Algorithm.cpp.o

Implementations/Algorithm.i: Implementations/Algorithm.cpp.i
.PHONY : Implementations/Algorithm.i

# target to preprocess a source file
Implementations/Algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Algorithm.cpp.i
.PHONY : Implementations/Algorithm.cpp.i

Implementations/Algorithm.s: Implementations/Algorithm.cpp.s
.PHONY : Implementations/Algorithm.s

# target to generate assembly for a file
Implementations/Algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Algorithm.cpp.s
.PHONY : Implementations/Algorithm.cpp.s

Implementations/Process.o: Implementations/Process.cpp.o
.PHONY : Implementations/Process.o

# target to build an object file
Implementations/Process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Process.cpp.o
.PHONY : Implementations/Process.cpp.o

Implementations/Process.i: Implementations/Process.cpp.i
.PHONY : Implementations/Process.i

# target to preprocess a source file
Implementations/Process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Process.cpp.i
.PHONY : Implementations/Process.cpp.i

Implementations/Process.s: Implementations/Process.cpp.s
.PHONY : Implementations/Process.s

# target to generate assembly for a file
Implementations/Process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/Implementations/Process.cpp.s
.PHONY : Implementations/Process.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exam1.dir/build.make CMakeFiles/Exam1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Exam1"
	@echo "... Implementations/Algorithm.o"
	@echo "... Implementations/Algorithm.i"
	@echo "... Implementations/Algorithm.s"
	@echo "... Implementations/Process.o"
	@echo "... Implementations/Process.i"
	@echo "... Implementations/Process.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

